apiVersion: certmanager.k8s.io/v0.6.0
kind: Certificate
metadata:
  name: federicoviscomi-com-tls
spec:
  secretName: federicoviscomi-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: federicoviscomi.com
  dnsName:
    - federicoviscomi.com
    - www.federicoviscomi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - federicoviscomi.com
          - www.federicoviscomi.com
