apiVersion: certmanager.k8s.io/v0.6.0
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.com
  dnsName:
    - federicoviscomi.com
    - www.federicoviscomi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - federicoviscomi.com
          - www.federicoviscomi.com
