apiVersion: certmanager.k8s.io/v0.6.0
kind: ClusterIssuer
metedata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'federicoviscomi@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
